version: "3"

services:
  strapi:
    image: strapi/strapi
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mongo
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      AUTHENTICATION_DATABASE: ${DATABASE_NAME}
    command: "strapi start" # Comment this out to enable development mode
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`strapi.docker.localhost`)" # Change me to your host name / domain name
      - "traefik.http.routers.strapi.entrypoints=web"
      # - "traefik.http.routers.strapi.tls.certresolver=secure"
    ports:
      - 1337
    volumes:
      - ./app:/srv/app
    networks:
      - traefik

volumes:
  letsencrypt:

networks:
  traefik:
    external: true
